### ISSUE TITLE
Adding media fails - 500 Internal Server Error / System.Exception: Method not found

### ISSUE THREAD

**Issue by Studentenfutter** [jellyfin/jellyfin-plugin-autoorganize#29]
When trying to add a movie automatic processing fails despite setting the name recognition patterns correctly, the movie shows up in the Activity log as failed.

If I try to add the movie manually, the Dialog and MovieDbProvider work. When I click OK, a dialog box shows up that states

`Error: Server returned status code 500 (Internal Server Error) but did not provide a more specific error message.`

Docker logfile additional info:

```
[15:33:04] [ERR] [28] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request
System.Exception: Method not found: 'System.String MediaBrowser.Model.Extensions.StringHelper.Replace(System.String, System.String, System.String, System.StringComparison)'.
   at Emby.AutoOrganize.Core.FileOrganizationService.PerformOrganization(MovieFileOrganizationRequest request)
```

<details>
<summary>Config Info</summary>

## OS & Jellyfin Version
```
[15:48:43] [INF] [1] Main: Jellyfin version: 10.5.0
[15:48:43] [INF] [1] Main: Arguments: ["/usr/lib/jellyfin/bin/jellyfin.dll", "--ffmpeg=/usr/lib/jellyfin-ffmpeg/ffmpeg"]
[15:48:43] [INF] [1] Main: Operating system: Linux
[15:48:43] [INF] [1] Main: Architecture: X64
[15:48:43] [INF] [1] Main: 64-Bit Process: True
[15:48:43] [INF] [1] Main: User Interactive: True
[15:48:43] [INF] [1] Main: Processor count: 4
```

## Plugins
```
[15:48:45] [INF] [1] App: Loaded assembly Jellyfin.Plugin.KodiSyncQueue, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null from /config/data/plugins/Kodi Sync Queue/Jellyfin.Plugin.KodiSyncQueue.dll
[15:48:45] [INF] [1] App: Loaded assembly LiteDB, Version=4.1.4.0, Culture=neutral, PublicKeyToken=4ee40123013c9f27 from /config/data/plugins/Kodi Sync Queue/LiteDB.dll
[15:48:45] [INF] [1] App: Loaded assembly Trakt, Version=7.0.0.0, Culture=neutral, PublicKeyToken=null from /config/data/plugins/Trakt/Trakt.dll
[15:48:45] [INF] [1] App: Loaded assembly Jellyfin.Plugin.OpenSubtitles, Version=7.0.0.0, Culture=neutral, PublicKeyToken=null from /config/data/plugins/Open Subtitles/Jellyfin.Plugin.OpenSubtitles.dll
[15:48:45] [INF] [1] App: Loaded assembly OpenSubtitlesHandler, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null from /config/data/plugins/Open Subtitles/OpenSubtitlesHandler.dll
[15:48:45] [INF] [1] App: Loaded assembly Jellyfin.Plugin.TMDbBoxSets, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null from /config/data/plugins/TMDb Box Sets/Jellyfin.Plugin.TMDbBoxSets.dll
[15:48:45] [INF] [1] App: Loaded assembly Emby.AutoOrganize, Version=5.0.0.0, Culture=neutral, PublicKeyToken=null from /config/data/plugins/Auto Organize/Emby.AutoOrganize.dll
```

</details>

**Comment by mark-monteiro** [comment]
I think my PR here should address this: #30 

In the meantime before the PR is merged I think you can switch back to the last stable release of the Jellyfin server, this should only be affecting users on nightly builds.

**Comment by QSchulz** [comment]
Hi,

Happens with newly released Jellyfin 10.5.0 and AutoOrganize 5.0.0. If that matters at all, I'm using the official docker image.

No TV show or movie can be processed successfully by AutoOrganize anymore.

You already have the log but attaching anyway:
```System.MissingMethodException: Method not found: 'System.String MediaBrowser.Model.Extensions.StringHelper.Replace(System.String, System.String, System.String, System.StringComparison)'.
   at Emby.AutoOrganize.Core.NameUtils.GetComparableName(String name)
   at Emby.AutoOrganize.Core.NameUtils.IsNameMatch(String name1, String name2)
   at Emby.AutoOrganize.Core.NameUtils.GetMatchScore(String sortedName, Nullable`1 year, String itemName, Nullable`1 itemProductionYear)
   at Emby.AutoOrganize.Core.NameUtils.GetMatchScore[T](String sortedName, Nullable`1 year, T item)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.ToArray()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.GetEnumerator()+MoveNext()
   at System.Linq.Enumerable.SelectIPartitionIterator`2.MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at Emby.AutoOrganize.Core.MovieFileOrganizer.GetMatchingMovie(String movieName, Nullable`1 movieYear, String targetFolder, FileOrganizationResult result, MovieFileOrganizationOptions options)
   at Emby.AutoOrganize.Core.MovieFileOrganizer.OrganizeMovie(String sourcePath, String movieName, Nullable`1 movieYear, MovieFileOrganizationOptions options, Boolean overwriteExisting, FileOrganizationResult result, CancellationToken cancellationToken)
   at Emby.AutoOrganize.Core.MovieFileOrganizer.OrganizeMovieFile(String path, MovieFileOrganizationOptions options, Boolean overwriteExisting, CancellationToken cancellationToken)
```

Let me know if there's anything I can do to help.

Thanks!

**Comment by samwathegreat** [comment]
I'm having the exact same issue as @QSchulz , using the exact same versions of Jellyfin and AutoOrganize.

**Comment by mark-monteiro** [comment]
Sorry for the delay in getting this out, but this should be addressed with #34 and we have tagged a new release v6 of this plugin: https://github.com/jellyfin/jellyfin-plugin-autoorganize/releases/tag/v6. Note that automatic plugin updates currently do not work on Windows, but a manual  workaround is listed here: https://github.com/jellyfin/jellyfin/issues/1623#issuecomment-538581937

Closing this for now, but feel free to comment here if you continue to have issues after updating and we can reopen this issue.

**Comment by QSchulz** [comment]
Thanks @mark-monteiro, no worries for the delay, that's part of FOSS. I'm very happy people are actually trying to fix the issue. Much appreciated!

I'd like to test but the v6 version isn't suggested by jellyfin (even after a reboot). Also, it seems that maybe we're missing an asset in the release? v3 to v5 have 3 assets, for v6 only two and we're missing the zip with the dll in it. Maybe Jellyfin plugin system looks for that? I genuinely don't know how it's working, so if it's just a matter of time for Jellyfin to detect the new version, please ignore :)

**Comment by mark-monteiro** [comment]
Hi @QSchulz sorry for the confusion, there have been some issues with the CI infrastructure the last few days and I don't think the release build has completed yet. I'm looking into it and will update here again if I figure out an update.

**Comment by mark-monteiro** [comment]
Okay the release is out finally now 😅 Reply again if it still isn't resolved, and I'll reopen this issue.

**Comment by samwathegreat** [comment]
@mark-monteiro I really want to use this, but the plug-in crashes my jellyfin server and I have to restore it from backup to be able to access it again.  Fortunately I have a very recent backup.  Is this working for anyone else?

**Comment by samwathegreat** [comment]
@mark-monteiro 

Further troubleshooting suggests this is directly related to the plugin.  The moment the plugin is installed, jellyfin becomes unresponsive.  Restarting the service via shell:  'service jellyfin restart' fails as well:

```
Mar 25 17:33:56 jellyfin jellyfin[2583]: [17:33:56] [INF] Loaded assembly Emby.AutoOrganize, Version=6.0.0.0, Culture=neutral, PublicKeyToken=null from /var/lib/jellyfin/plugins/Auto Organize/Emby.AutoOrganize.dll
Mar 25 17:33:56 jellyfin jellyfin[2583]: [17:33:56] [FTL] Error while starting server.
Mar 25 17:33:56 jellyfin jellyfin[2583]: System.IO.FileNotFoundException: Could not load file or assembly 'MediaBrowser.Common, Version=10.5.2.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
Mar 25 17:33:56 jellyfin jellyfin[2583]: File name: 'MediaBrowser.Common, Version=10.5.2.0, Culture=neutral, PublicKeyToken=null'
Mar 25 17:33:56 jellyfin jellyfin[2583]:    at System.Reflection.RuntimeAssembly.GetExportedTypes()
Mar 25 17:33:56 jellyfin jellyfin[2583]:    at Emby.Server.Implementations.ApplicationHost.GetTypes(IEnumerable`1 assemblies)+MoveNext()
Mar 25 17:33:56 jellyfin jellyfin[2583]:    at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
Mar 25 17:33:56 jellyfin jellyfin[2583]:    at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
Mar 25 17:33:56 jellyfin jellyfin[2583]:    at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
Mar 25 17:33:56 jellyfin jellyfin[2583]:    at Emby.Server.Implementations.ApplicationHost.DiscoverTypes()
Mar 25 17:33:56 jellyfin jellyfin[2583]:    at Emby.Server.Implementations.ApplicationHost.InitAsync(IServiceCollection serviceCollection)
Mar 25 17:33:56 jellyfin jellyfin[2583]:    at Jellyfin.Server.Program.StartApp(StartupOptions options)
Mar 25 17:33:56 jellyfin jellyfin[2583]: [17:33:56] [INF] Disposing CoreAppHost
Mar 25 17:33:57 jellyfin jellyfin[2583]: [17:33:57] [FTL] Unhandled Exception
Mar 25 17:33:57 jellyfin jellyfin[2583]: System.NullReferenceException: Object reference not set to an instance of an object.
Mar 25 17:33:57 jellyfin jellyfin[2583]:    at Emby.Server.Implementations.ApplicationHost.Dispose(Boolean dispose)
Mar 25 17:33:57 jellyfin jellyfin[2583]:    at Emby.Server.Implementations.ApplicationHost.Dispose()
Mar 25 17:33:57 jellyfin jellyfin[2583]:    at Jellyfin.Server.Program.StartApp(StartupOptions options)
Mar 25 17:33:57 jellyfin jellyfin[2583]:    at Jellyfin.Server.Program.<Main>(String[] args)
Mar 25 17:33:57 jellyfin jellyfin[2583]: Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
Mar 25 17:33:57 jellyfin jellyfin[2583]:    at Emby.Server.Implementations.ApplicationHost.Dispose(Boolean dispose)
Mar 25 17:33:57 jellyfin jellyfin[2583]:    at Emby.Server.Implementations.ApplicationHost.Dispose()
Mar 25 17:33:57 jellyfin jellyfin[2583]:    at Jellyfin.Server.Program.StartApp(StartupOptions options)
Mar 25 17:33:57 jellyfin jellyfin[2583]:    at Jellyfin.Server.Program.<Main>(String[] args)
Mar 25 17:33:57 jellyfin systemd[1]: jellyfin.service: Main process exited, code=killed, status=6/ABRT
```

Afterwards, I must restore from backup to be able to access jellyfin again.  Can you confirm this is related to the plugin?  Any further info and/or logs that would be helpful?

**Comment by mark-monteiro** [comment]
@samwathegreat I've confirmed that behaviour locally as well. I've opened a new issue to track it: https://github.com/jellyfin/jellyfin-plugin-autoorganize/issues/35

There have been some recent changes to how everything is built and released, I suspect this has something to do with that
