### ISSUE TITLE
Latest Release Crashes Server

### ISSUE THREAD

**Issue by mark-monteiro** [jellyfin/jellyfin-plugin-autoorganize#35]
Something with the NuGet dependencies has gone wrong with the build for the latest release. Resolution fails for the ` MediaBrowser.Common, Version=10.5.2.0` assembly.

I investigated a bit and deleting the plugin DLL does cause this error to go away and the server can start up.

Additional investigation has revealed that updating the server assembly versions [here](https://github.com/mark-monteiro/jellyfin/blob/master/SharedVersion.cs) to `10.5.2` resolves this error. However, I'm not familiar enough with the build system etc. to know if that is the correct solution here

```
Mar 25 17:33:56 jellyfin jellyfin[2583]: [17:33:56] [INF] Loaded assembly Emby.AutoOrganize, Version=6.0.0.0, Culture=neutral, PublicKeyToken=null from /var/lib/jellyfin/plugins/Auto Organize/Emby.AutoOrganize.dll
Mar 25 17:33:56 jellyfin jellyfin[2583]: [17:33:56] [FTL] Error while starting server.
Mar 25 17:33:56 jellyfin jellyfin[2583]: System.IO.FileNotFoundException: Could not load file or assembly 'MediaBrowser.Common, Version=10.5.2.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
Mar 25 17:33:56 jellyfin jellyfin[2583]: File name: 'MediaBrowser.Common, Version=10.5.2.0, Culture=neutral, PublicKeyToken=null'
Mar 25 17:33:56 jellyfin jellyfin[2583]:    at System.Reflection.RuntimeAssembly.GetExportedTypes()
Mar 25 17:33:56 jellyfin jellyfin[2583]:    at Emby.Server.Implementations.ApplicationHost.GetTypes(IEnumerable`1 assemblies)+MoveNext()
Mar 25 17:33:56 jellyfin jellyfin[2583]:    at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
Mar 25 17:33:56 jellyfin jellyfin[2583]:    at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
Mar 25 17:33:56 jellyfin jellyfin[2583]:    at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
Mar 25 17:33:56 jellyfin jellyfin[2583]:    at Emby.Server.Implementations.ApplicationHost.DiscoverTypes()
Mar 25 17:33:56 jellyfin jellyfin[2583]:    at Emby.Server.Implementations.ApplicationHost.InitAsync(IServiceCollection serviceCollection)
Mar 25 17:33:56 jellyfin jellyfin[2583]:    at Jellyfin.Server.Program.StartApp(StartupOptions options)
```

**Comment by mark-monteiro** [comment]
@joshuaboniface When you have the chance, I'm sure you could provide some insight here

**Comment by mark-monteiro** [comment]
This was fixed with https://github.com/jellyfin/jellyfin/pull/2656
