### ISSUE TITLE
Error organizing episode

### ISSUE THREAD

**Issue by MrNuggelz** [jellyfin/jellyfin-plugin-autoorganize#7]
When I try to run the organizer nothing happens and the following error is printed in the log:

> [2019-03-09 23:44:31.273 +00:00] [ERR] Error organizing episode "/some/path/to/a/file"
System.NullReferenceException: Object reference not set to an instance of an object.
   at Emby.AutoOrganize.Core.FileOrganizationService.SaveResult(FileOrganizationResult result, CancellationToken cancellationToken)
   at Emby.AutoOrganize.Core.EpisodeFileOrganizer.OrganizeEpisodeFile(String path, TvFileOrganizationOptions options, CancellationToken cancellationToken)
   at Emby.AutoOrganize.Core.TvFolderOrganizer.Organize(TvFileOrganizationOptions options, CancellationToken cancellationToken, IProgress`1 progress)

**Comment by MrNuggelz** [comment]
I also noticed an error that is thrown when the plugin is initialized
```
[22:32:00] [ERR] Error initializing auto-organize database
System.TypeInitializationException: The type initializer for 'Emby.AutoOrganize.Data.BaseSqliteRepository' threw an exception. ---> System.IO.FileNotFoundException: Could not load file or assembly 'SQLitePCL.pretty, Version=1.1.8.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

   --- End of inner exception stack trace ---
   at Emby.AutoOrganize.Data.BaseSqliteRepository..ctor(ILogger logger)
   at Emby.AutoOrganize.Data.SqliteFileOrganizationRepository..ctor(ILogger logger, IServerApplicationPaths appPaths, IJsonSerializer json)
   at Emby.AutoOrganize.PluginEntryPoint.GetRepository()
   at Emby.AutoOrganize.PluginEntryPoint.RunAsync()
```
