### ISSUE TITLE
InternalServer Error while pressing organize button

### ISSUE THREAD

**Issue by ssbarnea** [jellyfin/jellyfin-plugin-autoorganize#9]
```
[2019-03-24 15:38:39.033 +00:00] [INF] "HTTP SUBSCRIBE" "http://192.168.33.201:8096/dlna/241d21ac60e446c481cfc8d959d9c839/contentdirectory/events". UserAgent: ""
[2019-03-24 15:38:39.033 +00:00] [INF] HTTP Response 200 to "192.168.33.120". Time: "1""ms". "http://192.168.33.201:8096/dlna/241d21ac60e446c481cfc8d959d9c839/contentdirectory/events" ""
[2019-03-24 15:38:40.109 +00:00] [INF] "HTTP POST" "http://192.168.33.201:8096/emby/ScheduledTasks/Running/1ec5b785c4111045fc22055e467e2fff". UserAgent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:66.0) Gecko/20100101 Firefox/66.0"
[2019-03-24 15:38:40.110 +00:00] [INF] Executing "Organize new media files"
[2019-03-24 15:38:40.110 +00:00] [INF] HTTP Response 204 to "192.168.33.114". Time: "1""ms". "http://192.168.33.201:8096/emby/ScheduledTasks/Running/1ec5b785c4111045fc22055e467e2fff" ""
[2019-03-24 15:38:40.112 +00:00] [INF] Sorting file "/media/incoming/The Lobster (2015)/The Lobster (2015).mkv"
[2019-03-24 15:38:40.117 +00:00] [INF] "HTTP GET" "http://192.168.33.201:8096/emby/ScheduledTasks?IsEnabled=true". UserAgent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:66.0) Gecko/20100101 Firefox/66.0"
[2019-03-24 15:38:40.118 +00:00] [INF] HTTP Response 200 to "192.168.33.114". Time: "1""ms". "http://192.168.33.201:8096/emby/ScheduledTasks?IsEnabled=true" ""
[2019-03-24 15:38:40.193 +00:00] [WRN] Unable to find movie in library matching name The Lobster
[2019-03-24 15:38:40.194 +00:00] [ERR] Error organizing file "/media/incoming/The Lobster (2015)/The Lobster (2015).mkv"
System.NullReferenceException: Object reference not set to an instance of an object.
   at Emby.AutoOrganize.Core.FileOrganizationService.GetResult(String id)
   at Emby.AutoOrganize.Core.FileOrganizationService.GetResultBySourcePath(String path)
   at Emby.AutoOrganize.Core.MovieFileOrganizer.OrganizeMovieFile(String path, MovieFileOrganizationOptions options, Boolean overwriteExisting, CancellationToken cancellationToken)
[2019-03-24 15:38:40.194 +00:00] [ERR] Error organizing episode "/media/incoming/The Lobster (2015)/The Lobster (2015).mkv"
System.NullReferenceException: Object reference not set to an instance of an object.
   at Emby.AutoOrganize.Core.FileOrganizationService.SaveResult(FileOrganizationResult result, CancellationToken cancellationToken)
   at Emby.AutoOrganize.Core.MovieFileOrganizer.OrganizeMovieFile(String path, MovieFileOrganizationOptions options, Boolean overwriteExisting, CancellationToken cancellationToken)
   at Emby.AutoOrganize.Core.MovieFolderOrganizer.Organize(MovieFileOrganizationOptions options, CancellationToken cancellationToken, IProgress`1 progress)
[2019-03-24 15:38:40.194 +00:00] [INF] Sorting file "/media/incoming/Kal Ho Naa Ho -.mkv"
[2019-03-24 15:38:40.195 +00:00] [WRN] Unable to find movie in library matching name Kal Ho Naa Ho -
[2019-03-24 15:38:40.196 +00:00] [ERR] Error organizing file "/media/incoming/Kal Ho Naa Ho -.mkv"
System.NullReferenceException: Object reference not set to an instance of an object.
   at Emby.AutoOrganize.Core.FileOrganizationService.GetResult(String id)
   at Emby.AutoOrganize.Core.FileOrganizationService.GetResultBySourcePath(String path)
   at Emby.AutoOrganize.Core.MovieFileOrganizer.OrganizeMovieFile(String path, MovieFileOrganizationOptions options, Boolean overwriteExisting, CancellationToken cancellationToken)
[2019-03-24 15:38:40.196 +00:00] [ERR] Error organizing episode "/media/incoming/Kal Ho Naa Ho -.mkv"
System.NullReferenceException: Object reference not set to an instance of an object.
   at Emby.AutoOrganize.Core.FileOrganizationService.SaveResult(FileOrganizationResult result, CancellationToken cancellationToken)
   at Emby.AutoOrganize.Core.MovieFileOrganizer.OrganizeMovieFile(String path, MovieFileOrganizationOptions options, Boolean overwriteExisting, CancellationToken cancellationToken)
   at Emby.AutoOrganize.Core.MovieFolderOrganizer.Organize(MovieFileOrganizationOptions options, CancellationToken cancellationToken, IProgress`1 progress)
[2019-03-24 15:38:40.196 +00:00] [INF] Queueing task "RefreshMediaLibraryTask"
[2019-03-24 15:38:40.196 +00:00] [INF] "Organize new media files" Completed after 0 minute(s) and 0 seconds
[2019-03-24 15:38:40.197 +00:00] [INF] Executing "Scan media library"
[2019-03-24 15:38:40.197 +00:00] [INF] ExecuteQueuedTasks
[2019-03-24 15:38:40.197 +00:00] [INF] Stopping directory watching for path "/media/Movies"
[2019-03-24 15:38:40.219 +00:00] [INF] Validating media library
[2019-03-24 15:38:40.232 +00:00] [INF] "Scan media library" Completed after 0 minute(s) and 0 seconds
[2019-03-24 15:38:40.232 +00:00] [INF] Watching directory /media/Movies
[2019-03-24 15:38:40.233 +00:00] [INF] ExecuteQueuedTasks
[2019-03-24 15:38:40.260 +00:00] [INF] "HTTP GET" "http://192.168.33.201:8096/emby/Library/FileOrganization?StartIndex=0&Limit=50". UserAgent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:66.0) Gecko/20100101 Firefox/66.0"
[2019-03-24 15:38:40.261 +00:00] [ERR] Error processing request
System.NullReferenceException: Object reference not set to an instance of an object.
   at Emby.AutoOrganize.Core.FileOrganizationService.GetResults(FileOrganizationResultQuery query)
   at Emby.AutoOrganize.Api.FileOrganizationService.Get(GetFileOrganizationActivity request)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.Execute(Type serviceType, IRequest request, Object instance, Object requestDto, String requestName)
   at Emby.Server.Implementations.Services.ServiceController.Execute(HttpListenerHost appHost, Object requestDto, IRequest req)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost appHost, IRequest httpReq, IResponse httpRes, ILogger logger, String operationName, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
[2019-03-24 15:38:40.262 +00:00] [INF] HTTP Response 500 to "192.168.33.114". Time: "2""ms". "http://192.168.33.201:8096/emby/Library/FileOrganization?StartIndex=0&Limit=50" ""
[2019-03-24 15:38:45.431 +00:00] [ERR] Error creating http port map
MediaBrowser.Model.Net.HttpException: The remote server returned an error: (500) Internal Server Error. ---> System.Net.WebException: The remote server returned an error: (500) Internal Server Error.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
   --- End of inner exception stack trace ---
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsyncInternal(HttpRequestOptions options, String httpMethod)
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsync(HttpRequestOptions options, String httpMethod)
   at Mono.Nat.Upnp.UpnpNatDevice.CreatePortMap(Mapping mapping)
   at Emby.Server.Implementations.EntryPoints.ExternalPortForwarding.CreateRules(INatDevice device)
```

**Comment by joshuaboniface** [comment]
Might be fixed by #15? Please try out v4 and let us know!
